---
- user:
    name: "{{ atlassian_user_name }}"
    shell: /usr/sbin/nologin
    comment: "Atlassian nologin User"
    append: yes
  become: true

- unarchive:
    src: "https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{ jira_version }}.tar.gz"
    dest: "/home/{{ atlassian_user_name }}/"
    remote_src: True
  become_user: "{{ atlassian_user_name }}"
  become: true

- file:
    src: "/home/{{ atlassian_user_name }}/atlassian-jira-software-{{ jira_version }}-standalone"
    dest: "/home/{{ atlassian_user_name }}/{{ jira_directory }}"
    state: link
  become_user: "{{ atlassian_user_name }}"
  become: true

- file:
    path: "/home/{{ atlassian_user_name }}/{{ jira_home_directory }}"
    state: directory
    mode: "u=rwx,go-rwx"
  become_user: "{{ atlassian_user_name }}"
  become: true

- template:
    src: ../templates/atlassian-jira/WEB-INF/classes/jira-application.properties
    dest: "/home/{{ atlassian_user_name }}/{{ jira_directory }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
    mode: 0644
    force: yes
  become_user: "{{ atlassian_user_name }}"
  become: true

- template:
    src: ../templates/conf/server.xml
    dest: "/home/{{ atlassian_user_name }}/{{ jira_directory }}/conf/server.xml"
    mode: 0644
    force: yes
  become_user: "{{ atlassian_user_name }}"
  become: true


- template:
    src: ../templates/etc/init.d/jira.j2
    dest: /etc/init.d/jira
    owner: "{{ atlassian_user_name }}"
    mode: "u=rwx,go=rx"
  become: true

- get_url:
   url: "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ java_mysql_connector_version }}.tar.gz"
   dest: "{{ default_download_directory }}"
   owner: "{{ atlassian_user_name }}"
   group: "{{ atlassian_user_name }}"
  become: true

- unarchive:
   src: "{{ default_download_directory }}/mysql-connector-java-{{ java_mysql_connector_version }}.tar.gz"
   dest: "{{ default_download_directory }}"
   remote_src: True
   owner: "{{ atlassian_user_name }}"
   group: "{{ atlassian_user_name }}"
  become: true


- name: JIRA ROLE | Copy mysql-connector-java
  command: "chdir={{ default_download_directory }}/mysql-connector-java-{{ java_mysql_connector_version }} cp mysql-connector-java-{{ java_mysql_connector_version }}-bin.jar /home/{{ atlassian_user_name }}/{{ jira_directory }}/lib"
  become_user: "{{ atlassian_user_name }}"
  become: true

- name: JIRA ROLE | Update script list
  command: update-rc.d -f jira defaults
  become: true

- name: JIRA ROLE | Ensure jira is restarted
  action: service name=jira state=restarted
  become: true